# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
include:
  - homeassistant/docker-compose.yml
  - mosquitto/docker-compose.yml
  - pihole/docker-compose.yml
  - postgres/docker-compose.yml
  - synapse/docker-compose.yml
  - syncthing/docker-compose.yml
  - zigbee2mqtt/docker-compose.yml
